import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Sidebar is fixed, main is shifted by its width */}
        <Sidebar />
        <main
          className="min-h-screen overflow-y-auto px-5"
          style={{ marginLeft: "var(--sidebar-w)", background: "#F6EEF8" }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
